version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.9.0
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: apache-airflow-providers-postgres
    entrypoint: >
      bash -c "airflow db init && \
               airflow users create --username admin --firstname Admin --lastname User --role Admin \
                 --email admin@example.com --password admin && \
               airflow scheduler"
    depends_on:
      - postgres

  airflow-web:
    image: apache/airflow:2.9.0
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    ports:
      - "8080:8080"
    command: webserver
    depends_on:
      - airflow-init

  airflow-worker:
    image: apache/airflow:2.9.0
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: celery worker
    depends_on:
      - airflow-web

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "pip install streamlit psycopg2-binary sqlalchemy
               && streamlit run src/nlpipeline/streamlit_app.py --server.port 8501 --server.enableCORS false"
    ports:
      - "8501:8501"
    volumes:
      - .:/workspace
    working_dir: /workspace
